### PR TITLE
docs: add iQIYI to ADOPTERS.md

### PR DESCRIPTION
**Pull request by wangxiaoq**
## Description

add iQIYI to ADOPTERS.md

### CODE REVIEW

**Review by jim3ma — DISMISSED** [review]
LGTM

**Comment by jim3ma** [comment]
The lint is failed, can you fix it?
```
ADOPTERS.md:97:71 MD047/single-trailing-newline Files should end with a single newline character
```

**Comment by wangxiaoq** [comment]
> The lint is failed, can you fix it?
> 
> ```
> ADOPTERS.md:97:71 MD047/single-trailing-newline Files should end with a single newline character
> ```

fixed

**Review by gaius-qi — APPROVED** [review]
LGTM

**Pull request merged**
