### PR TITLE
preheat image supports authentication and parse multi manifest mediatype

### PR DESCRIPTION
**Pull request by Panlq**
## Description
1. support preheat images from private registry correctly
2. parse multi-mediatype manifest
3. support specific platforms for manifest list

## Related Issue

https://github.com/dragonflyoss/Dragonfly2/issues/769

## Motivation and Context

Supports direct preheating of private registry images

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by gaius-qi** [comment]
@Panlq Please fix lint.

**Comment by Panlq** [comment]
> @Panlq Please fix lint.
https://github.com/dragonflyoss/Dragonfly2/actions/runs/6601592490/job/18066447978
It seems that the execution of the lint timeout. I have fixed the lint during the first action execution.

**Review by gaius-qi — CHANGES_REQUESTED** [review]
@Panlq Please add E2E testing in https://github.com/dragonflyoss/Dragonfly2/blob/main/test/e2e/manager/preheat.go.

**Comment by Panlq** [comment]
> @Panlq Please add E2E testing in https://github.com/dragonflyoss/Dragonfly2/blob/main/test/e2e/manager/preheat.go.

Changes in new features are compatible with the original e2e test content！so there is no need to add anything else.？

**Comment by gaius-qi** [comment]
> > @Panlq Please add E2E testing in https://github.com/dragonflyoss/Dragonfly2/blob/main/test/e2e/manager/preheat.go.
> 
> Changes in new features are compatible with the original e2e test content！so there is no need to add anything else？ This PR only affects the image type and does not affect the file type preheating tasks. I have added unit tests for the image type: https://github.com/dragonflyoss/Dragonfly2/pull/2819/files#diff-081c3a63e6dd230c53072d96260e02bab12cb187c4d75b018c2c0052652a951a

@Panlq Please add E2E testing in https://github.com/dragonflyoss/Dragonfly2/blob/main/test/e2e/manager/preheat.go.

**Comment by Panlq** [comment]
I know, what I want to express is that the original e2e has already involved image type testing, and is also compatible with new code.

I am familiar with the existing e2e use cases and add the scenario of specifying platform parameters. The account and password cannot be written in them.

**Comment by gaius-qi** [comment]
> I know, what I want to express is that the original e2e has already involved image type testing, and is also compatible with new code.
> 
> I am familiar with the existing e2e use cases and add the scenario of specifying platform parameters. The auth(account and password) cannot be written in them

You can send me the image, and I will upload it to dragonfly's group in docker hub for E2E testing. I think you should need to add multi-platform E2E test cases.

**Comment by gaius-qi** [comment]
> I know, what I want to express is that the original e2e has already involved image type testing, and is also compatible with new code.
> 
> I am familiar with the existing e2e use cases and add the scenario of specifying platform parameters. The auth(account and password) cannot be written in them

@Panlq
First you can send me the image and version, and I will upload it to dragonfly's group in docker hub for E2E testing. I think you should need to add multi-platform E2E test cases.

**Comment by Panlq** [comment]
> > I know, what I want to express is that the original e2e has already involved image type testing, and is also compatible with new code.
> > I am familiar with the existing e2e use cases and add the scenario of specifying platform parameters. The auth(account and password) cannot be written in them
> 
> @Panlq First you can send me the image and version, and I will upload it to dragonfly's group in docker hub for E2E testing. I think you should need to add multi-platform E2E test cases.

ok, I think I can use busybox:latest  (amd64/arm64) to write e2e use cases

**Comment by gaius-qi** [comment]
> > > I know, what I want to express is that the original e2e has already involved image type testing, and is also compatible with new code.
> > > I am familiar with the existing e2e use cases and add the scenario of specifying platform parameters. The auth(account and password) cannot be written in them
> > 
> > 
> > @Panlq First you can send me the image and version, and I will upload it to dragonfly's group in docker hub for E2E testing. I think you should need to add multi-platform E2E test cases.
> 
> ok, I think I can use busybox:latest (amd64/arm64) to write e2e use cases

You can use `dragonflyoss/scheduler:v2.1.0`(amd64/arm64) to write e2e use cases.

**Comment by Panlq** [comment]
> > > > I know, what I want to express is that the original e2e has already involved image type testing, and is also compatible with new code.
> > > > I am familiar with the existing e2e use cases and add the scenario of specifying platform parameters. The auth(account and password) cannot be written in them
> > > 
> > > 
> > > @Panlq First you can send me the image and version, and I will upload it to dragonfly's group in docker hub for E2E testing. I think you should need to add multi-platform E2E test cases.
> > 
> > 
> > ok, I think I can use busybox:latest (amd64/arm64) to write e2e use cases
> 
> You can use `dragonflyoss/scheduler:v2.1.0(amd64/arm64)` to write e2e use cases.

ok, let me

> > > > I know, what I want to express is that the original e2e has already involved image type testing, and is also compatible with new code.
> > > > I am familiar with the existing e2e use cases and add the scenario of specifying platform parameters. The auth(account and password) cannot be written in them
> > > 
> > > 
> > > @Panlq First you can send me the image and version, and I will upload it to dragonfly's group in docker hub for E2E testing. I think you should need to add multi-platform E2E test cases.
> > 
> > 
> > ok, I think I can use busybox:latest (amd64/arm64) to write e2e use cases
> 
> You can use `dragonflyoss/scheduler:v2.1.0(amd64/arm64)` to write e2e use cases.

ok, I have added the e2e test case, please re-execute ci!

**Comment by Panlq** [comment]
> ok, I have added the e2e test case, please re-execute ci!  @gaius-qi

**Review by gaius-qi — APPROVED** [review]
LGTM

**Pull request merged**
