### PR TITLE
spelling error, just a little mistake

### PR DESCRIPTION
**Pull request by lilongfeng0902**
## Description

modify a simple spelling mistake.

## Related Issue
nothing

## Motivation and Context
Make a contribution to the commity from small things.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation Update (if none of the other choices apply)

## Checklist:

- [x] Code compiles correctly.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jim3ma** [comment]
Please sign off the commit by `git commit --amend -s` or follow: https://github.com/dragonflyoss/Dragonfly2/pull/976/checks?check_run_id=4724071075

**Comment by lilongfeng0902** [comment]
> Please sign off the commit by `git commit --amend -s` or follow: https://github.com/dragonflyoss/Dragonfly2/pull/976/checks?check_run_id=4724071075



> Please sign off the commit by `git commit --amend -s` or follow: https://github.com/dragonflyoss/Dragonfly2/pull/976/checks?check_run_id=4724071075

Yeah, I have done that.  I have learned this from "dragonflyoss/Dragonfly". I have commited a PR about  "dragonflyoss/Dragonfly", could you also check it ? ^0^……

**Review by jim3ma — APPROVED** [review]
LGTM

**Review by gaius-qi — APPROVED** [review]
LGTM

**Pull request merged**
