### PR TITLE
fix: adjust the configuration check sequence

### PR DESCRIPTION
**Pull request by zc2638**
## Description

Adjust the configuration check sequence.
Before the service starts to initialize, verify the configuration content first, which can ensure a smoother subsequent process.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by gaius-qi** [comment]
Please help to fix this problem in the manager, dfget and dfcache modules together. Thx.

**Review by gaius-qi — CHANGES_REQUESTED** [review]
Please help to fix this problem in the manager, dfget and dfcache modules together. Thx.

**Comment by zc2638** [comment]
I just started looking at the code so I ignored the other modules.
Done.
@gaius-qi

**Review by gaius-qi — APPROVED** [review]
LGTM

**Review by 1037husterljx — APPROVED** [review]

**Pull request merged**
