### PR TITLE
Update typo in local_storage.go

### PR DESCRIPTION
**Pull request by guoguodan**
UPDATE: seked-->sought

### CODE REVIEW

**Review by jim3ma — APPROVED** [review]
LGTM

**Comment by jim3ma** [comment]
Please sign off your commit by "git commit --amend -s" and force push again.

**Review by hyy0322 — APPROVED** [review]

**Review by jim3ma — CHANGES_REQUESTED** [review]
Please sign off your commit by "git commit --amend -s" and force push again.

**Review by gaius-qi — APPROVED** [review]
Please sign off next time.

**Pull request merged**
