### PR TITLE
test : add unit tests for fdqnHostName

### PR DESCRIPTION
**Pull request by khareyash05**
## Description

increase test coverage for `pkg/net/fqdn.go`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by gaius-qi — CHANGES_REQUESTED** [review]
Fix lint.

**Comment by khareyash05** [comment]
Hi @gaius-qi Can you pls help me find error.It is taking a lot of time for me to find the error.

**Comment by yxxhero** [comment]
@khareyash05 
image

**Comment by yxxhero** [comment]
@khareyash05 please fix DCO issue.

**Comment by khareyash05** [comment]
> @khareyash05 please fix DCO issue.

do i revert the code and then push a signed commit??

**Comment by khareyash05** [comment]
@yxxhero Could you please redirect to PR #2395 I have added the code

**Pull request closed without merging**
