### PR TITLE
refactor: scheduler task SizeScope

### PR DESCRIPTION
**Pull request by gaius-qi**
Signed-off-by: Gaius <gaius.qi@gmail.com>

## Description
- Refactor `task.SizeScope`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Review by yxxhero — DISMISSED** [review]

**Review by KubeStacker — APPROVED** [review]
LGTM

**Comment by eryugey** [comment]
I'd recommend that split this patch into two commits, one adds more validations to scheduler proto, the other refactors task SizeScope with commit log explains why the refactor is needed. As the proto change and the refactor are two different tasks, we'd better use different patches.

P.S.
Currently most commits in dragonfly2 repo lack detailed commit log explaining what's the purpose of the change they've done, I think we could improve that step by step, and this could make it easier for reviewer to review and for others to learn dragonfly2 code from the commit log.

**Review by cndoit18 — APPROVED** [review]
LGTM

**Comment by gaius-qi** [comment]
> I'd recommend that split this patch into two commits, one adds more validations to scheduler proto, the other refactors task SizeScope with commit log explains why the refactor is needed. As the proto change and the refactor are two different tasks, we'd better use different patches.
> 
> P.S. Currently most commits in dragonfly2 repo lack detailed commit log explaining what's the purpose of the change they've done, I think we could improve that step by step, and this could make it easier for reviewer to review and for others to learn dragonfly2 code from the commit log.

- Refactor scheduler `task.SizeScope`: #1287 
- Change scheduler peer result validation: #1288

**Review by hyy0322 — APPROVED** [review]

**Pull request merged**
