### PR TITLE
[WIP] Add peerMgr, taskMgr and cdn_util test cases

### PR DESCRIPTION
**Pull request by wyoshmx**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist:

- [x] Code compiles correctly.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by yxxhero** [comment]
@wyoshmx 
You only have one commit incorrectly signed off! To fix, first ensure you have a local copy of your branch by checking out the pull request locally via command line. Next, head to your local branch and run:

```
git commit --amend --no-edit --signoff
```

Now your commits will have your sign off. Next run

```
git push --force-with-lease origin wys
```
Commit sha: 195ada2, Author: wyoshmx, Committer: wyoshmx; The sign-off is missing.

Thanks very mush

**Comment by yxxhero** [comment]
@wyoshmx  require rebase. Thanks very much.

**Comment by yxxhero** [comment]
@wyoshmx pleas fix lint error

**Comment by wyoshmx** [comment]
Add peerMgr, taskMgr and cdn_util test cases

**Comment by wyoshmx** [comment]
Add peerMgr, taskMgr and cdn_util test cases

**Pull request closed without merging**
