### PR TITLE
fix make build-dfget error, syscall package can't use on the m1 chip …

### PR DESCRIPTION
**Pull request by 1037husterljx**
fix make build-dfget error, syscall package can't use on the m1 chip … 

## Description

use x/sys replace syscall 

## Related Issue

https://github.com/dragonflyoss/Dragonfly2/issues/1374#issue-1269003813 

## Motivation and Context

syscall package can't use on the m1 chip 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by gaius-qi** [comment]
Please signing commits, refer to https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits.

**Review by gaius-qi — APPROVED** [review]
LGTM

**Review by cndoit18 — APPROVED** [review]
LGTM

**Review by bigerous — DISMISSED** [review]
LGTM

**Review by gaius-qi — APPROVED** [review]

**Review by jim3ma — CHANGES_REQUESTED** [review]
Please test build dfget in linux aarch64

**Comment by 1037husterljx** [comment]
> Please test build dfget in linux aarch64

test build dfget linux/darwin arm64/amd64 success

**Comment by 1037husterljx** [comment]
> > Please test build dfget in linux aarch64
> 
> test build dfget linux/darwin arm64/amd64 success

**Comment by 1037husterljx** [comment]
> Please test build dfget in linux aarch64
test build dfget linux/darwin arm64/amd64 success

**Pull request merged**
