### PR TITLE
fix: use hostname when fqdn hostname not found

### PR DESCRIPTION
**Pull request by power-more**
Signed-off-by: zhaoshang <zhaoshangsjtu@linux.alibaba.com>

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by yxxhero** [comment]
@power-more Please fix the lint issue. Thanks very much.

**Comment by gaius-qi** [comment]
Please rebase main branch.

**Comment by power-more** [comment]
> Please rebase main branch.
done

**Comment by gaius-qi** [comment]
> It's more like a new feature to me, so "feat: " prefix looks like a better prefix.
> 
> And please write commit log to describe why using hostname as FQDNhostname is not an issue.

cc @power-more

**Comment by gaius-qi** [comment]
Fix https://github.com/dragonflyoss/Dragonfly2/pull/1435

**Pull request closed without merging**
