### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by guoguodan**
edit error word: verison -> "version"

### CODE REVIEW

**Review by garenwen — APPROVED** [review]
LGTM

**Comment by allencloud** [comment]
@guoguodan please help solve the  DCO. Thanks.

**Comment by gaius-qi** [comment]
> @guoguodan please help solve the DCO. Thanks.

+1

**Review by gaius-qi — CHANGES_REQUESTED** [review]
Please help solve the DCO. Thanks.

**Pull request closed without merging**
